name = "fapleaks3"
compatibility_date = "2026-05-07"

[assets]
directory = "./fapleaks2/fapleaks-fixed"
binding = "ASSETS"

[[routes]]
pattern = "futurewaveventures.click/*"
zone_name = "futurewaveventures.click"
